const channelTypes = {
  // FETCH_CHANNEL
  FETCH_CHANNEL_START: 'FETCH_CHANNEL_START',
  FETCH_CHANNEL_SUCCESS: 'FETCH_CHANNEL_SUCCESS',
  FETCH_CHANNEL_FAILURE: 'FETCH_CHANNEL_FAILURE',

  // FETCH_CHANNELS
  FETCH_CHANNELS_START: 'FETCH_CHANNELS_START',
  FETCH_CHANNELS_SUCCESS: 'FETCH_CHANNELS_SUCCESS',
  FETCH_CHANNELS_FAILURE: 'FETCH_CHANNELS_FAILURE',

  // CREATE_CHANNEL
  CREATE_CHANNEL_START: 'CREATE_CHANNEL_START',
  CREATE_CHANNEL_SUCCESS: 'CREATE_CHANNEL_SUCCESS',
  CREATE_CHANNEL_FAILURE: 'CREATE_CHANNEL_FAILURE',
}

export default channelTypes;