const channelTypes = {
  // FETCH_CHANNEL
  FETCH_CHANNEL_START: 'FETCH_CHANNEL_START',
  FETCH_CHANNEL_SUCCESS: 'FETCH_CHANNEL_SUCCESS',
  FETCH_CHANNEL_FAILURE: 'FETCH_CHANNEL_FAILURE',

  // FETCH_CHANNELS
  FETCH_CHANNELS_START: 'FETCH_CHANNELS_START',
  FETCH_CHANNELS_SUCCESS: 'FETCH_CHANNELS_SUCCESS',
  FETCH_CHANNELS_FAILURE: 'FETCH_CHANNELS_FAILURE',

  // CREATE_CHANNEL
  CREATE_CHANNEL_START: 'CREATE_CHANNEL_START',
  CREATE_CHANNEL_SUCCESS: 'CREATE_CHANNEL_SUCCESS',
  CREATE_CHANNEL_FAILURE: 'CREATE_CHANNEL_FAILURE',

  // EDIT_CHANNEL
  EDIT_CHANNEL_FAILURE: 'EDIT_CHANNEL_FAILURE',

  // DELETE_CHANNEL
  DELETE_CHANNEL_FAILURE: 'DELETE_CHANNEL_FAILURE',
  // TRASH_CHANNEL
  TRASH_CHANNEL_FAILURE: 'TRASH_CHANNEL_FAILURE',

  // CLEAR
  CLEAR: 'CLEAR'
}

export default channelTypes;