version: '3'
  
services:
  api:
    build: ./api
    container_name: forum-api
    # command: npm run start
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - POSTGRES_PORT=5432
      - POSTGRES_USER=nikolay
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_HOST='api_db'
      - POSTGRES_DB=mydb
      - POSTGRES_URL=postgres://nikolay:secretpassword@api_db:5432/mydb
    depends_on:
      - api_db
    networks:
      - forum-network

  api_db:
    image: 'postgres'
    container_name: forum-api-db
    environment:
      - POSTGRES_PASSWORD=secretpassword
    # volumes: 
    #   - ./pgdata:/var/libs/postgresql/data
      

    

networks:
  forum-network:
    driver: bridge