const topicTypes = {
  // FETCH_TOPICS
  FETCH_TOPICS_START: 'FETCH_TOPICS_START',
  FETCH_TOPICS_SUCCESS: 'FETCH_TOPICS_SUCCESS',
  FETCH_TOPICS_FAILURE: 'FETCH_TOPICS_FAILURE',

  // FETCH_TOPIC
  FETCH_TOPIC_START: 'FETCH_TOPIC_START',
  FETCH_TOPIC_SUCCESS: 'FETCH_TOPIC_SUCCESS',
  FETCH_TOPIC_FAILURE: 'FETCH_TOPIC_FAILURE',

  // CREATE_TOPIC
  CREATE_TOPIC_START: 'CREATE_TOPIC_START',
  CREATE_TOPIC_SUCCESS: 'CREATE_TOPIC_SUCCESS',
  CREATE_TOPIC_FAILURE: 'CREATE_TOPIC_FAILURE',
}

export default topicTypes;