const userTypes = {
  // // SET CURRENT USER
  // SET_CURRENT_USER_START: 'SET_CURRENT_USER_START',
  // SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  // SET_CURRENT_USER_FAILURE: 'SET_CURRENT_USER_FAILURE',

  // CHECK_AUTH
  CHECK_AUTH_START: 'CHECK_AUTH_START',
  CHECK_AUTH_SUCCESS: 'CHECK_AUTH_SUCCESS',
  CHECK_AUTH_FAILURE: 'CHECK_AUTH_FAILURE',

  // LOGIN
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // REGISTER
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  // LOGOUT
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export default userTypes;
